---
# tasks file for gitlab
- name: Instalar Dependencias
  apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: latest
  loop:
    - curl 
    - ca-certificates
    - openssh-server 
    - postfix 

- name: Baixando script de repositorios do Gitlab 
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh

- name: Executando script de repositorio
  command: bash /tmp/gitlab_install_repository.sh 

- name: Instalando Gitlab CE
  apt: 
    name: gitlab-ce 
    update_cache: yes 
    state: latest
...
